[package]
name = "roguelike-tutorial"
version = "0.1.0"
authors = ["Igor Kamyshev <igor@kamyshev.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.13"
rand = "0.3.9"
